from typing import Any

class WebSocketException(Exception): ...
class WebSocketProtocolException(WebSocketException): ...
class WebSocketPayloadException(WebSocketException): ...
class WebSocketConnectionClosedException(WebSocketException): ...
class WebSocketTimeoutException(WebSocketException): ...
class WebSocketProxyException(WebSocketException): ...

class WebSocketBadStatusException(WebSocketException):
    status_code: Any = ...
    def __init__(self, message, status_code) -> None: ...

class WebSocketAddressException(WebSocketException): ...
